version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.161.44
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  mysql:
    image: mysql:5.7
    ports:
      - "3316:3316"
    environment:
      MYSQL_ROOT_PASSWORD: hanhaigang@126
    volumes:
      - $(pwd)/sql:/docker-entrypoint-initdb.d
    depends_on:
      - kafka
  stream_cutter:
    image: qtt/stream_cutter
    ports:
      - "3000:3000"
    depends_on:
      - mysql
  logserver4qukanlog:
    image: qtt/logserver4qukanlog
    ports:
      - "5000:5000"
    depends_on:
      - stream_cutter
